### PR TITLE
Remove F5 networking plugin

### PR DESCRIPTION
**Pull request by borisroman**
Integration tests running: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/68
Merge together with: https://github.com/MissionCriticalCloud/cosmic-core/pull/127

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
@borisroman @bheuvel This breaks the Service Offering tab. Tested also when this PR was reverted and then it works again. Could you please investigate/fix before next release? Thx!

screen shot 2016-05-13 at 21 22 59

**Comment by remibergsma** [comment]
Never mind, clearing cache resolved it. `find /data/git/$HOSTNAME/cosmic/cosmic-client -name \*.gz | xargs rm -f`.

**Comment by remibergsma** [comment]
And the problem is back! :-(

**Comment by remibergsma** [comment]
screen shot 2016-05-17 at 13 36 05

Will fix it.

**Pull request merged**
