### PR TITLE
First part of the Java 8 + Maven refactor

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR makes the cosmic-client Maven compliant.

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
Ping @borisroman @miguelaferreira 

Build in the bubble:

```
[INFO] Installing /data/git/cs1/cosmic/cosmic-client/pom.xml to /root/.m2/repository/cloud/cosmic/cloud-client-ui/5.0.0-SNAPSHOT/cloud-client-ui-5.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.850s
[INFO] Finished at: Mon Feb 08 18:47:01 GMT 2016
[INFO] Final Memory: 29M/359M
[INFO] ------------------------------------------------------------------------
[root@cs1 cosmic-client]#
```

**Comment by miguelaferreira** [comment]
go build

**Pull request merged**
