### PR TITLE
Fix dashboard fixlatest typo

### PR DESCRIPTION
**Pull request by remibergsma**
Backport of ACS PR 1462
Author: Rohit Yadav rohit.yadav@shapeblue.com

### CODE REVIEW

**Comment by remibergsma** [comment]
`fetchLatest` parameter was missing, it is included now:

screen shot 2016-04-04 at 21 05 09 pm

**Comment by miguelaferreira** [comment]
This build is failing because the slave that builds it cannot fetch the latest cosmic artifacts. There are two reasons for that: the slave has never built cosmic not we have nexus working as a source of artifacts. We'll fix this tomorrow.

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Pull request merged**
