### PR TITLE
Copy the scripts into the WEB-INF/classes directory instead of utilities

### PR DESCRIPTION
**Pull request by wilderrodrigues**

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@remibergsma 

Integration tests running here -> https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/34/

**Comment by wilderrodrigues** [comment]
Integration tests were running for 1 day and 16 hours. Although they were passing, I decided to abort the build because it was taking too long.  

Rebuilding it here -> https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-tracking-repo-branch-build/

**Comment by remibergsma** [comment]
Ping @borisroman Can you have a look at this please. Would prevent generating archive of db scripts when we drop our war.

**Comment by remibergsma** [comment]
Built a war and verified the `db` scripts are in there now:

image

👍

**Pull request merged**
